export const southernAfrica = [
  {
    id: 0,
    image: "/botswana.svg",
    name: "Botswana",
    capital: "Gaborone",
    currency: "Botswana Pula",
  },
  {
    id: 1,
    image: "/eswatini.svg",
    name: "Eswatini",
    capital: "Mbabane",
    currency: "Botswana Pula",
  },
  {
    id: 2,
    image: "/lesotho.svg",
    name: "Lesotho",
    capital: "Maseru",
    currency: "Botswana Pula",
  },
  {
    id: 3,
    image: "/malawi.svg",
    name: "Malawi",
    capital: "Lilongwe",
    currency: "Botswana Pula",
  },
  {
    id: 4,
    image: "/mozambique.svg",
    name: "Mozambique",
    capital: "Maputo",
    currency: "Botswana Pula",
  },
  {
    id: 5,
    image: "/namibia.svg",
    name: "Namibia",
    capital: "Windhoek",
    currency: "Botswana Pula",
  },
  {
    id: 6,
    image: "/south-africa.svg",
    name: "South Africa",
    capital: "Capital city: Pretoria, Cape Town, and Bloemfontein",
    currency: "Botswana Pula",
  },
  {
    id: 7,
    image: "/zambia.svg",
    name: "Zambia",
    capital: "Lusaka",
    currency: "Botswana Pula",
  },
  {
    id: 8,
    image: "/zimbabwe.svg",
    name: "Zimbabwe",
    capital: "Harare",
    currency: "Botswana Pula",
  },
];
export const westernAfrica = [
  {
    id: 0,
    image: "/angola.svg",
    name: "Angola",
    capital: "Luanda",
    currency: "Angolan Kwanza ",
  },
  {
    id: 1,
    image: "/ivory-coast.svg",
    name: "Côte d'Ivoire ",
    capital: "Abidjan",
    currency: "West African CFA Franc",
  },
  {
    id: 2,
    image: "/drc.svg",
    name: "DRC",
    capital: "Kinshasa",
    currency: "Congolese Franc",
  },
  {
    id: 3,
    image: "/ghana.svg",
    name: "Ghana",
    capital: "Accra",
    currency: "Ghana Cedi",
  },
  {
    id: 4,
    image: "/nigeria.svg",
    name: "Nigeria",
    capital: "Abuja",
    currency: "Nigerian Naira",
  },
];
export const easternAfrica = [
  {
    id: 0,
    image: "/ethiopia.svg",
    name: "Ethopia",
    capital: "Addis Ababa",
    currency: "Ethiopian Birr",
  },
  {
    id: 1,
    image: "/kenya.svg",
    name: "Kenya",
    capital: "Nairobi",
    currency: "Kenyan Shilling",
  },
  {
    id: 2,
    image: "/south-sudan.svg",
    name: "South Sudan",
    capital: "Juba",
    currency: "South Sudanese Pound",
  },
  {
    id: 3,
    image: "/tanzania.svg",
    name: "Tanzania",
    capital: "Dodoma",
    currency: "Tanzanian Shilling ",
  },
  {
    id: 4,
    image: "/uganda.svg",
    name: "Uganda",
    capital: "Kampala",
    currency: "Ugandan Shilling",
  },
];
export const international = [
  {
    id: 0,
    image: "/china.svg",
    name: "Beijing",
    capital: "Capital city of China",
    currency: "Chinese Yuan",
  },
  {
    id: 1,
    image: "/uae.svg",
    name: "Dubai",
    capital: "Capital city of Emirate of Dubai",
    currency: "Emirati Dirham",
  },
  {
    id: 2,
    image: "/isle-of-man.svg",
    name: "Isle of man",
    capital: "Capital City:Douglas",
    currency: "Manx Pound",
  },

  {
    id: 3,
    image: "/jersey.svg",
    name: "Jersey",
    capital: "Capital City:St Helier",
    currency: "Pound Sterling",
  },
  {
    id: 4,
    image: "/uk.svg",
    name: "London",
    capital: "Capital City of England, UK",
    currency: "Pound Sterling",
  },
  {
    id: 5,
    image: "/mauritius.svg",
    name: "Mauritius",
    capital: "Capital City:Port Louis",
    currency: "Mauritian Ruppee",
  },
  {
    id: 6,
    image: "/us.svg",
    name: "New York",
    capital: "Capital City:Albany",
    currency: "United States Dollar",
  },
];
